// Augments the Env interface generated by `wrangler types` (worker-configuration.d.ts).
// This file survives `wrangler types` regeneration — keep optional/unbound bindings here.
// SUBSCRIPTION_RATE_LIMITER is intentionally NOT bound in wrangler.toml (free-tier friendly);
// subscriptions.ts uses it with try/catch for graceful degradation when absent.

interface RateLimitResult {
	success: boolean;
}

interface RateLimiter {
	limit(input: { key: string }): Promise<RateLimitResult>;
}

interface Env {
	SUBSCRIPTION_RATE_LIMITER?: RateLimiter;
}

// Raw-imported migration SQL (tests import migration files as text).
declare module '*.sql?raw' {
	const content: string;
	export default content;
}
